### ISSUE TITLE
Not necessary an issue, but rather a credentials-related question

### ISSUE THREAD

**Issue by vorbidan** [blacksmith-community/postgresql-forge-boshrelease#10]
`postgresql-forge-boshrelease/jobs/postgresql-blacksmith-plans/templates/plans/cluster/credentials.yml`

defines the `db_name` credentials key. 

When trying to use this service instance as a backing db with cloudfoundry stratos, it is not able to properly construct the connection, because stratos is looking for a `dbname` (no underscore) key in credentials.

Now, I am not sure what is right and what is wrong, but it would have been nice if there was a consensus

**Comment by jhunt** [comment]
Yeah, we should support stratos' naming mechanism as well.
