### ISSUE TITLE
Unable to override the persistent disk in the cluster plan.

### ISSUE THREAD

**Issue by elric392** [blacksmith-community/postgresql-forge-boshrelease#5]
Override of the persistent disk type not possible in the _**cluster**_ plan.

> instance_groups:
  - name: postgresql
    instances: (( grab meta.instances ))
    azs: (( grab meta.azs || meta.default.azs ))
    networks: [name: (( grab meta.net || meta.default.azs ))]
    stemcell: default

    vm_type: (( grab meta.size ))
    persistent_disk_type: default

**Comment by antitux** [comment]
I referenced a fix for this in #8
